# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from dbconnection import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 550)
        MainWindow.setMinimumSize(QtCore.QSize(950, 550))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(950, 550))
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 950, 550))
        self.stackedWidget.setMinimumSize(QtCore.QSize(950, 550))
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setMinimumSize(QtCore.QSize(950, 550))
        self.loginPage.setObjectName("loginPage")
        self.loginLeftFrame = QtWidgets.QFrame(self.loginPage)
        self.loginLeftFrame.setGeometry(QtCore.QRect(0, 0, 450, 581))
        self.loginLeftFrame.setMinimumSize(QtCore.QSize(400, 550))
        self.loginLeftFrame.setStyleSheet("background-color: rgb(102, 150, 200);")
        self.loginLeftFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.loginLeftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginLeftFrame.setObjectName("loginLeftFrame")
        self.loginIntroLabel1 = QtWidgets.QLabel(self.loginLeftFrame)
        self.loginIntroLabel1.setGeometry(QtCore.QRect(80, 100, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.loginIntroLabel1.setFont(font)
        self.loginIntroLabel1.setStyleSheet("color: rgb(255, 255, 255)")
        self.loginIntroLabel1.setObjectName("loginIntroLabel1")
        self.loginIntroLabel2 = QtWidgets.QLabel(self.loginLeftFrame)
        self.loginIntroLabel2.setGeometry(QtCore.QRect(85, 150, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.loginIntroLabel2.setFont(font)
        self.loginIntroLabel2.setStyleSheet("color: rgb(255, 255, 255)")
        self.loginIntroLabel2.setObjectName("loginIntroLabel2")
        self.loginIntroLabel3 = QtWidgets.QLabel(self.loginLeftFrame)
        self.loginIntroLabel3.setGeometry(QtCore.QRect(80, 260, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.loginIntroLabel3.setFont(font)
        self.loginIntroLabel3.setStyleSheet("color: rgb(255, 255, 255)")
        self.loginIntroLabel3.setObjectName("loginIntroLabel3")
        self.loginIntroLabel4 = QtWidgets.QLabel(self.loginLeftFrame)
        self.loginIntroLabel4.setGeometry(QtCore.QRect(170, 290, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.loginIntroLabel4.setFont(font)
        self.loginIntroLabel4.setStyleSheet("color: rgb(255, 255, 255)")
        self.loginIntroLabel4.setObjectName("loginIntroLabel4")
        self.loginRightFrame = QtWidgets.QFrame(self.loginPage)
        self.loginRightFrame.setGeometry(QtCore.QRect(440, 0, 550, 551))
        self.loginRightFrame.setMinimumSize(QtCore.QSize(550, 550))
        self.loginRightFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.loginRightFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.loginRightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginRightFrame.setObjectName("loginRightFrame")
        self.userIcon = QtWidgets.QLabel(self.loginRightFrame)
        self.userIcon.setGeometry(QtCore.QRect(190, 70, 101, 91))
        self.userIcon.setText("")
        self.userIcon.setPixmap(QtGui.QPixmap("user_icon.png"))
        self.userIcon.setScaledContents(True)
        self.userIcon.setObjectName("userIcon")
        self.usernameField = QtWidgets.QLineEdit(self.loginRightFrame)
        self.usernameField.setGeometry(QtCore.QRect(130, 220, 231, 31))
        self.usernameField.setStyleSheet("border: 1px solid rgb(117, 117, 117);\n"
"border-radius: 2px;")
        self.usernameField.setText("")
        self.usernameField.setObjectName("usernameField")
        self.passwordField = QtWidgets.QLineEdit(self.loginRightFrame)
        self.passwordField.setGeometry(QtCore.QRect(130, 310, 231, 31))
        self.passwordField.setStyleSheet("border: 1px solid rgb(117, 117, 117);\n"
"border-radius: 2px;")
        self.passwordField.setObjectName("passwordField")
        self.usernameLabel = QtWidgets.QLabel(self.loginRightFrame)
        self.usernameLabel.setGeometry(QtCore.QRect(130, 190, 81, 19))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setStyleSheet("color: rgb(117, 117, 117)")
        self.usernameLabel.setObjectName("usernameLabel")
        self.passwordLabel = QtWidgets.QLabel(self.loginRightFrame)
        self.passwordLabel.setGeometry(QtCore.QRect(130, 280, 81, 19))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setStyleSheet("color: rgb(117, 117, 117)")
        self.passwordLabel.setObjectName("passwordLabel")
        self.loginButton = QtWidgets.QPushButton(self.loginRightFrame)
        self.loginButton.setGeometry(QtCore.QRect(130, 370, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("QPushButton#loginButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(102, 150, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover#loginButton{\n"
"    background-color: rgb(113, 167, 221)\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.stackedWidget.addWidget(self.loginPage)
        self.registerPage = QtWidgets.QWidget()
        self.registerPage.setObjectName("registerPage")
        self.stackedWidget.addWidget(self.registerPage)
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setMinimumSize(QtCore.QSize(900, 550))
        self.mainPage.setObjectName("mainPage")
        self.main_TopFframe = QtWidgets.QFrame(self.mainPage)
        self.main_TopFframe.setGeometry(QtCore.QRect(0, 0, 951, 51))
        self.main_TopFframe.setMinimumSize(QtCore.QSize(951, 51))
        self.main_TopFframe.setStyleSheet("background-color: rgb(102, 150, 200);")
        self.main_TopFframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_TopFframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_TopFframe.setObjectName("main_TopFframe")
        self.label = QtWidgets.QLabel(self.main_TopFframe)
        self.label.setGeometry(QtCore.QRect(20, 17, 91, 19))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.main_BottomFrame = QtWidgets.QFrame(self.mainPage)
        self.main_BottomFrame.setGeometry(QtCore.QRect(0, 50, 950, 501))
        self.main_BottomFrame.setMinimumSize(QtCore.QSize(950, 501))
        self.main_BottomFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_BottomFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_BottomFrame.setObjectName("main_BottomFrame")
        self.main_MenuFrame = QtWidgets.QFrame(self.main_BottomFrame)
        self.main_MenuFrame.setGeometry(QtCore.QRect(0, 0, 181, 561))
        self.main_MenuFrame.setMinimumSize(QtCore.QSize(181, 561))
        self.main_MenuFrame.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.main_MenuFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_MenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_MenuFrame.setObjectName("main_MenuFrame")
        self.main_MenuButtonsFrame = QtWidgets.QFrame(self.main_MenuFrame)
        self.main_MenuButtonsFrame.setGeometry(QtCore.QRect(0, 60, 201, 441))
        self.main_MenuButtonsFrame.setMinimumSize(QtCore.QSize(181, 441))
        self.main_MenuButtonsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_MenuButtonsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_MenuButtonsFrame.setObjectName("main_MenuButtonsFrame")
        self.dashboardButton = QtWidgets.QPushButton(self.main_MenuButtonsFrame)
        self.dashboardButton.setGeometry(QtCore.QRect(0, 0, 181, 51))
        self.dashboardButton.setMinimumSize(QtCore.QSize(181, 0))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.dashboardButton.setFont(font)
        self.dashboardButton.setStyleSheet("QPushButton#dashboardButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(117, 117, 117);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover#dashboardButton{\n"
"    background-color: rgb(113, 167, 221)\n"
"}")
        self.dashboardButton.setObjectName("dashboardButton")
        self.transactionsButton = QtWidgets.QPushButton(self.main_MenuButtonsFrame)
        self.transactionsButton.setGeometry(QtCore.QRect(0, 50, 181, 51))
        self.transactionsButton.setMinimumSize(QtCore.QSize(181, 0))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.transactionsButton.setFont(font)
        self.transactionsButton.setStyleSheet("QPushButton#transactionsButton{\n"
"    color: rgb(117, 117, 117);\n"
"    background-color: rgb(247, 247, 247);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover#transactionsButton{\n"
"    background-color: rgb(113, 167, 221)\n"
"}")
        self.transactionsButton.setObjectName("transactionsButton")
        self.main_MenuBurgerFrame = QtWidgets.QFrame(self.main_MenuFrame)
        self.main_MenuBurgerFrame.setGeometry(QtCore.QRect(0, 0, 181, 61))
        self.main_MenuBurgerFrame.setMinimumSize(QtCore.QSize(181, 61))
        self.main_MenuBurgerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_MenuBurgerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_MenuBurgerFrame.setObjectName("main_MenuBurgerFrame")
        self.sideMenuLabel = QtWidgets.QLabel(self.main_MenuBurgerFrame)
        self.sideMenuLabel.setGeometry(QtCore.QRect(20, 30, 68, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sideMenuLabel.setFont(font)
        self.sideMenuLabel.setStyleSheet("color: rgb(117, 117, 117)")
        self.sideMenuLabel.setObjectName("sideMenuLabel")
        self.main_ContenFrame = QtWidgets.QFrame(self.main_BottomFrame)
        self.main_ContenFrame.setGeometry(QtCore.QRect(180, 0, 771, 501))
        self.main_ContenFrame.setMinimumSize(QtCore.QSize(771, 501))
        self.main_ContenFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.main_ContenFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_ContenFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_ContenFrame.setObjectName("main_ContenFrame")
        self.mainScreens = QtWidgets.QStackedWidget(self.main_ContenFrame)
        self.mainScreens.setGeometry(QtCore.QRect(0, 0, 771, 501))
        self.mainScreens.setMinimumSize(QtCore.QSize(771, 501))
        self.mainScreens.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mainScreens.setObjectName("mainScreens")
        self.dashboardScreen = QtWidgets.QWidget()
        self.dashboardScreen.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dashboardScreen.setObjectName("dashboardScreen")
        self.mainScreens.addWidget(self.dashboardScreen)
        self.transactionScreen = QtWidgets.QWidget()
        self.transactionScreen.setObjectName("transactionScreen")
        self.transactionStackedWidget = QtWidgets.QStackedWidget(self.transactionScreen)
        self.transactionStackedWidget.setGeometry(QtCore.QRect(0, 0, 771, 501))
        self.transactionStackedWidget.setObjectName("transactionStackedWidget")
        self.viewTransactions = QtWidgets.QWidget()
        self.viewTransactions.setObjectName("viewTransactions")
        self.addTransactionButtonFrame = QtWidgets.QFrame(self.viewTransactions)
        self.addTransactionButtonFrame.setGeometry(QtCore.QRect(-1, 419, 771, 101))
        self.addTransactionButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.addTransactionButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.addTransactionButtonFrame.setObjectName("addTransactionButtonFrame")
        self.addTransactionButton = QtWidgets.QPushButton(self.addTransactionButtonFrame)
        self.addTransactionButton.setGeometry(QtCore.QRect(270, 20, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.addTransactionButton.setFont(font)
        self.addTransactionButton.setStyleSheet("QPushButton#addTransactionButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(102, 150, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover#addTransactionButton{\n"
"    background-color: rgb(113, 167, 221)\n"
"}")
        self.addTransactionButton.setObjectName("addTransactionButton")
        self.transactionContentFrame = QtWidgets.QFrame(self.viewTransactions)
        self.transactionContentFrame.setGeometry(QtCore.QRect(0, 110, 771, 311))
        self.transactionContentFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transactionContentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transactionContentFrame.setObjectName("transactionContentFrame")
        self.transactionInstanceFrame = QtWidgets.QFrame(self.transactionContentFrame)
        self.transactionInstanceFrame.setGeometry(QtCore.QRect(30, 20, 701, 51))
        self.transactionInstanceFrame.setStyleSheet("background-color: rgb(247, 247, 247);\n"
"border-radius:5px;")
        self.transactionInstanceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transactionInstanceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transactionInstanceFrame.setObjectName("transactionInstanceFrame")
        self.productLabel = QtWidgets.QLabel(self.transactionInstanceFrame)
        self.productLabel.setGeometry(QtCore.QRect(10, 15, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.productLabel.setFont(font)
        self.productLabel.setStyleSheet("color: rgb(117, 117, 117)")
        self.productLabel.setObjectName("productLabel")
        self.customerLabel = QtWidgets.QLabel(self.transactionInstanceFrame)
        self.customerLabel.setGeometry(QtCore.QRect(230, 15, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.customerLabel.setFont(font)
        self.customerLabel.setStyleSheet("color: rgb(117, 117, 117)")
        self.customerLabel.setObjectName("customerLabel")
        self.priceLabel = QtWidgets.QLabel(self.transactionInstanceFrame)
        self.priceLabel.setGeometry(QtCore.QRect(490, 15, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.priceLabel.setFont(font)
        self.priceLabel.setStyleSheet("color: rgb(117, 117, 117)")
        self.priceLabel.setObjectName("priceLabel")
        self.pushButton = QtWidgets.QPushButton(self.transactionInstanceFrame)
        self.pushButton.setGeometry(QtCore.QRect(620, 12, 31, 31))
        self.pushButton.setStyleSheet("QPushButton#transactionsButton{\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover#transactionsButton{\n"
"    \n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("remove_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(22, 22))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.transactionInstanceFrame)
        self.pushButton_2.setGeometry(QtCore.QRect(660, 11, 31, 31))
        self.pushButton_2.setStyleSheet("QPushButton#transactionsButton{\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover#transactionsButton{\n"
"    \n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("edit_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.transactionHeaderFrame = QtWidgets.QFrame(self.viewTransactions)
        self.transactionHeaderFrame.setGeometry(QtCore.QRect(0, 0, 771, 111))
        self.transactionHeaderFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transactionHeaderFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transactionHeaderFrame.setObjectName("transactionHeaderFrame")
        self.transactionLabel = QtWidgets.QLabel(self.transactionHeaderFrame)
        self.transactionLabel.setGeometry(QtCore.QRect(40, 20, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.transactionLabel.setFont(font)
        self.transactionLabel.setStyleSheet("color: rgb(117, 117, 117)")
        self.transactionLabel.setObjectName("transactionLabel")
        self.transactionLabel2 = QtWidgets.QLabel(self.transactionHeaderFrame)
        self.transactionLabel2.setGeometry(QtCore.QRect(40, 70, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.transactionLabel2.setFont(font)
        self.transactionLabel2.setStyleSheet("color: rgb(117, 117, 117)")
        self.transactionLabel2.setObjectName("transactionLabel2")
        self.transactionLabel3 = QtWidgets.QLabel(self.transactionHeaderFrame)
        self.transactionLabel3.setGeometry(QtCore.QRect(260, 70, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.transactionLabel3.setFont(font)
        self.transactionLabel3.setStyleSheet("color: rgb(117, 117, 117)")
        self.transactionLabel3.setObjectName("transactionLabel3")
        self.transactionLabel4 = QtWidgets.QLabel(self.transactionHeaderFrame)
        self.transactionLabel4.setGeometry(QtCore.QRect(520, 70, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.transactionLabel4.setFont(font)
        self.transactionLabel4.setStyleSheet("color: rgb(117, 117, 117)")
        self.transactionLabel4.setObjectName("transactionLabel4")
        self.transactionStackedWidget.addWidget(self.viewTransactions)
        self.addTransactionPage = QtWidgets.QWidget()
        self.addTransactionPage.setObjectName("addTransactionPage")
        self.addTransactionFrame = QtWidgets.QFrame(self.addTransactionPage)
        self.addTransactionFrame.setGeometry(QtCore.QRect(0, 0, 771, 501))
        self.addTransactionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.addTransactionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.addTransactionFrame.setObjectName("addTransactionFrame")
        self.addTransactionLabel = QtWidgets.QLabel(self.addTransactionFrame)
        self.addTransactionLabel.setGeometry(QtCore.QRect(300, 40, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.addTransactionLabel.setFont(font)
        self.addTransactionLabel.setStyleSheet("color: rgb(117, 117, 117)")
        self.addTransactionLabel.setObjectName("addTransactionLabel")
        self.addProductComboBox = QtWidgets.QComboBox(self.addTransactionFrame)
        self.addProductComboBox.setGeometry(QtCore.QRect(250, 120, 251, 31))
        self.addProductComboBox.setObjectName("addProductComboBox")
        self.addProductComboBox.addItem("")
        self.addProductComboBox.addItem("")
        self.addProductComboBox.addItem("")
        self.addProductComboBox.addItem("")
        self.addProductComboBox.addItem("")
        self.addTransactionProductLabel = QtWidgets.QLabel(self.addTransactionFrame)
        self.addTransactionProductLabel.setGeometry(QtCore.QRect(250, 90, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.addTransactionProductLabel.setFont(font)
        self.addTransactionProductLabel.setStyleSheet("color: rgb(117, 117, 117)")
        self.addTransactionProductLabel.setObjectName("addTransactionProductLabel")
        self.addTransactionDescInput = QtWidgets.QLineEdit(self.addTransactionFrame)
        self.addTransactionDescInput.setGeometry(QtCore.QRect(250, 180, 251, 31))
        self.addTransactionDescInput.setObjectName("addTransactionDescInput")
        self.addTransactionCustInput = QtWidgets.QLineEdit(self.addTransactionFrame)
        self.addTransactionCustInput.setGeometry(QtCore.QRect(250, 240, 251, 31))
        self.addTransactionCustInput.setObjectName("addTransactionCustInput")
        self.addTransactionPriceInput = QtWidgets.QLineEdit(self.addTransactionFrame)
        self.addTransactionPriceInput.setGeometry(QtCore.QRect(250, 300, 251, 31))
        self.addTransactionPriceInput.setObjectName("addTransactionPriceInput")
        self.addTransactionQuantity = QtWidgets.QSpinBox(self.addTransactionFrame)
        self.addTransactionQuantity.setGeometry(QtCore.QRect(380, 360, 61, 25))
        self.addTransactionQuantity.setObjectName("addTransactionQuantity")
        self.addTransactionQuantityLabel = QtWidgets.QLabel(self.addTransactionFrame)
        self.addTransactionQuantityLabel.setGeometry(QtCore.QRect(250, 360, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.addTransactionQuantityLabel.setFont(font)
        self.addTransactionQuantityLabel.setStyleSheet("color: rgb(117, 117, 117)")
        self.addTransactionQuantityLabel.setObjectName("addTransactionQuantityLabel")
        self.addTransactionSaveButton = QtWidgets.QPushButton(self.addTransactionFrame)
        self.addTransactionSaveButton.setGeometry(QtCore.QRect(250, 420, 111, 41))
        self.addTransactionSaveButton.setStyleSheet("QPushButton#addTransactionSaveButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(102, 150, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover#addTransactionSaveButton{\n"
"    background-color: rgb(113, 167, 221)\n"
"}")
        self.addTransactionSaveButton.setObjectName("addTransactionSaveButton")
        self.addTransactionCancelButton = QtWidgets.QPushButton(self.addTransactionFrame)
        self.addTransactionCancelButton.setGeometry(QtCore.QRect(395, 420, 111, 41))
        self.addTransactionCancelButton.setStyleSheet("QPushButton#addTransactionCancelButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 123, 79);\n"
"    border: 0px solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover#addTransactionCancelButton{\n"
"    background-color: rgb(255, 119, 65);\n"
"}")
        self.addTransactionCancelButton.setObjectName("addTransactionCancelButton")
        self.transactionStackedWidget.addWidget(self.addTransactionPage)
        self.editTransactionPage = QtWidgets.QWidget()
        self.editTransactionPage.setObjectName("editTransactionPage")
        self.editTransactionFrame = QtWidgets.QFrame(self.editTransactionPage)
        self.editTransactionFrame.setGeometry(QtCore.QRect(0, -10, 771, 501))
        self.editTransactionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.editTransactionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.editTransactionFrame.setObjectName("editTransactionFrame")
        self.editProductComboBox = QtWidgets.QComboBox(self.editTransactionFrame)
        self.editProductComboBox.setGeometry(QtCore.QRect(240, 120, 251, 31))
        self.editProductComboBox.setObjectName("editProductComboBox")
        self.editProductComboBox.addItem("")
        self.editProductComboBox.addItem("")
        self.editProductComboBox.addItem("")
        self.editProductComboBox.addItem("")
        self.editProductComboBox.addItem("")
        self.editTransactionCustInput = QtWidgets.QLineEdit(self.editTransactionFrame)
        self.editTransactionCustInput.setGeometry(QtCore.QRect(240, 240, 251, 31))
        self.editTransactionCustInput.setObjectName("editTransactionCustInput")
        self.editTransactionQuantity = QtWidgets.QSpinBox(self.editTransactionFrame)
        self.editTransactionQuantity.setGeometry(QtCore.QRect(370, 360, 61, 25))
        self.editTransactionQuantity.setObjectName("editTransactionQuantity")
        self.editTransactionProductLabel = QtWidgets.QLabel(self.editTransactionFrame)
        self.editTransactionProductLabel.setGeometry(QtCore.QRect(240, 90, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.editTransactionProductLabel.setFont(font)
        self.editTransactionProductLabel.setStyleSheet("color: rgb(117, 117, 117)")
        self.editTransactionProductLabel.setObjectName("editTransactionProductLabel")
        self.editTransactionDescInput = QtWidgets.QLineEdit(self.editTransactionFrame)
        self.editTransactionDescInput.setGeometry(QtCore.QRect(240, 180, 251, 31))
        self.editTransactionDescInput.setObjectName("editTransactionDescInput")
        self.editTransactionQuantityLabel = QtWidgets.QLabel(self.editTransactionFrame)
        self.editTransactionQuantityLabel.setGeometry(QtCore.QRect(240, 360, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.editTransactionQuantityLabel.setFont(font)
        self.editTransactionQuantityLabel.setStyleSheet("color: rgb(117, 117, 117)")
        self.editTransactionQuantityLabel.setObjectName("editTransactionQuantityLabel")
        self.editTransactionPriceInput = QtWidgets.QLineEdit(self.editTransactionFrame)
        self.editTransactionPriceInput.setGeometry(QtCore.QRect(240, 300, 251, 31))
        self.editTransactionPriceInput.setObjectName("editTransactionPriceInput")
        self.editTransactionUpdateButton = QtWidgets.QPushButton(self.editTransactionFrame)
        self.editTransactionUpdateButton.setGeometry(QtCore.QRect(240, 420, 111, 41))
        self.editTransactionUpdateButton.setStyleSheet("QPushButton#editTransactionUpdateButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(102, 150, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover#editTransactionUpdateButton{\n"
"    background-color: rgb(113, 167, 221)\n"
"}")
        self.editTransactionUpdateButton.setObjectName("editTransactionUpdateButton")
        self.editTransactionCancelButton = QtWidgets.QPushButton(self.editTransactionFrame)
        self.editTransactionCancelButton.setGeometry(QtCore.QRect(385, 420, 111, 41))
        self.editTransactionCancelButton.setStyleSheet("QPushButton#editTransactionCancelButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 123, 79);\n"
"    border: 0px solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover#editTransactionCancelButton{\n"
"    background-color: rgb(255, 119, 65);\n"
"}")
        self.editTransactionCancelButton.setObjectName("editTransactionCancelButton")
        self.editTransactionLabel = QtWidgets.QLabel(self.editTransactionFrame)
        self.editTransactionLabel.setGeometry(QtCore.QRect(300, 40, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.editTransactionLabel.setFont(font)
        self.editTransactionLabel.setStyleSheet("color: rgb(117, 117, 117)")
        self.editTransactionLabel.setObjectName("editTransactionLabel")
        self.transactionStackedWidget.addWidget(self.editTransactionPage)
        self.mainScreens.addWidget(self.transactionScreen)
        self.stackedWidget.addWidget(self.mainPage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.mainScreens.setCurrentIndex(0)
        self.transactionStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        ####CONNECT TO DATABASE
        DBConnection()

        
        ###NAVIGATION
        self.loginButton.clicked.connect(lambda: self.login())
        self.dashboardButton.clicked.connect(lambda: self.mainScreens.setCurrentWidget(self.dashboardScreen))
        self.transactionsButton.clicked.connect(lambda: self.mainScreens.setCurrentWidget(self.transactionScreen))
        self.addTransactionButton.clicked.connect(lambda: self.transactionStackedWidget.setCurrentWidget(self.addTransactionPage))
        self.pushButton_2.clicked.connect(lambda: self.transactionStackedWidget.setCurrentWidget(self.editTransactionPage))
        
        
        self.addTransactionSaveButton.clicked.connect(lambda: self.addTransaction())
        self.addTransactionCancelButton.clicked.connect(lambda: self.transactionStackedWidget.setCurrentWidget(self.viewTransactions))

        #self.editTransactionUpdateButton.clicked.connect(lambda: self.transactionStackedWidget.setCurrentWidget(self.viewTransactions))
        self.editTransactionCancelButton.clicked.connect(lambda: self.transactionStackedWidget.setCurrentWidget(self.viewTransactions))

    def login(self):
        try:
             username = self.usernameField.text()
             password = self.passwordField.text()

             db = mdb.connect('localhost', 'root', '', 'jlneon')
             mycursor = db.cursor()
             query = "SELECT username, password FROM tbluser WHERE username LIKE '"+username+"' AND password LIKE '"+password+"'"
             mycursor.execute(query)
             result = mycursor.fetchone()

             if result == None:
                  print("Error logging in")
        
             else:
                  self.stackedWidget.setCurrentWidget(self.mainPage)
        
        except mdb.Error as e:
             print("Error")


    def addTransaction(self):
        try:
             product = self.addProductComboBox.currentText()
             description = self.addTransactionDescInput.text()
             customer = self.addTransactionCustInput.text()
             price = self.addTransactionPriceInput.text()
             quantity = self.addTransactionQuantity.value()

             db = mdb.connect('localhost', 'root', '', 'jlneon')
             mycursor = db.cursor()
             query = "INSERT INTO tblsales(product, description, customer_name, quantity, unitPrice) VALUES (%s,%s,%s,%s,%s)"
             values = (product, description, customer, quantity, price)        
             
             mycursor.execute(query, values)
             db.commit()
             print("successfuly added data")
             self.transactionStackedWidget.setCurrentWidget(self.viewTransactions)


        except mdb.Error as e:
             print("Error")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginIntroLabel1.setText(_translate("MainWindow", "Sales Automation"))
        self.loginIntroLabel2.setText(_translate("MainWindow", "Calendar Design"))
        self.loginIntroLabel3.setText(_translate("MainWindow", "Login to manage transactions "))
        self.loginIntroLabel4.setText(_translate("MainWindow", "efficiently"))
        self.usernameField.setPlaceholderText(_translate("MainWindow", " Username"))
        self.passwordField.setPlaceholderText(_translate("MainWindow", " Password"))
        self.usernameLabel.setText(_translate("MainWindow", "USERNAME"))
        self.passwordLabel.setText(_translate("MainWindow", "PASSWORD"))
        self.loginButton.setText(_translate("MainWindow", "SIGN IN"))
        self.label.setText(_translate("MainWindow", "JLNeon"))
        self.dashboardButton.setText(_translate("MainWindow", "Dashboard"))
        self.transactionsButton.setText(_translate("MainWindow", "Transactions"))
        self.sideMenuLabel.setText(_translate("MainWindow", "Menu"))
        self.addTransactionButton.setText(_translate("MainWindow", "Add Transaction"))
        self.productLabel.setText(_translate("MainWindow", "Tshirt Print"))
        self.customerLabel.setText(_translate("MainWindow", "Kevin Heart"))
        self.priceLabel.setText(_translate("MainWindow", "500"))
        self.transactionLabel.setText(_translate("MainWindow", "Transactions"))
        self.transactionLabel2.setText(_translate("MainWindow", "Product"))
        self.transactionLabel3.setText(_translate("MainWindow", "Customer"))
        self.transactionLabel4.setText(_translate("MainWindow", "Price"))
        self.addTransactionLabel.setText(_translate("MainWindow", "Add Transaction"))
        self.addProductComboBox.setCurrentText(_translate("MainWindow", "Tarpaulin Printing"))
        self.addProductComboBox.setItemText(0, _translate("MainWindow", "Tarpaulin Printing"))
        self.addProductComboBox.setItemText(1, _translate("MainWindow", "Sticker"))
        self.addProductComboBox.setItemText(2, _translate("MainWindow", "Shirt Printing"))
        self.addProductComboBox.setItemText(3, _translate("MainWindow", "Mug Printing"))
        self.addProductComboBox.setItemText(4, _translate("MainWindow", "ID Printing"))
        self.addTransactionProductLabel.setText(_translate("MainWindow", "Product"))
        self.addTransactionDescInput.setPlaceholderText(_translate("MainWindow", " Description"))
        self.addTransactionCustInput.setPlaceholderText(_translate("MainWindow", " Customer"))
        self.addTransactionPriceInput.setPlaceholderText(_translate("MainWindow", " Unit Price"))
        self.addTransactionQuantityLabel.setText(_translate("MainWindow", "Quantity"))
        self.addTransactionSaveButton.setText(_translate("MainWindow", "Save"))
        self.addTransactionCancelButton.setText(_translate("MainWindow", "Cancel"))
        self.editProductComboBox.setCurrentText(_translate("MainWindow", "Tarpaulin Printing"))
        self.editProductComboBox.setItemText(0, _translate("MainWindow", "Tarpaulin Printing"))
        self.editProductComboBox.setItemText(1, _translate("MainWindow", "Sticker"))
        self.editProductComboBox.setItemText(2, _translate("MainWindow", "Shirt Printing"))
        self.editProductComboBox.setItemText(3, _translate("MainWindow", "Mug Printing"))
        self.editProductComboBox.setItemText(4, _translate("MainWindow", "ID Printing"))
        self.editTransactionCustInput.setPlaceholderText(_translate("MainWindow", " Customer"))
        self.editTransactionProductLabel.setText(_translate("MainWindow", "Product"))
        self.editTransactionDescInput.setPlaceholderText(_translate("MainWindow", " Description"))
        self.editTransactionQuantityLabel.setText(_translate("MainWindow", "Quantity"))
        self.editTransactionPriceInput.setPlaceholderText(_translate("MainWindow", " Unit Price"))
        self.editTransactionUpdateButton.setText(_translate("MainWindow", "Update"))
        self.editTransactionCancelButton.setText(_translate("MainWindow", "Cancel"))
        self.editTransactionLabel.setText(_translate("MainWindow", "Edit Transaction"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
